In [1]:
from keras.datasets import cifar10
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout
from keras.layers.normalization import BatchNormalization
from tensorflow.keras.utils import to_categorical
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

In [2]:
# load data - 50k for training, 10k for testing
# 32x32 pixel images - 10 output classes
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

170508288/170498071 [==============================] - 2s 0us/step


In [3]:
print(X_train.shape)
print(X_test.shape)
print(y_test.shape)

# (50000, 32, 32, 3) 3 columns for 4-th element
# (10000, 32, 32, 3)
# (10000, 1)

print(np.unique(y_train))

(50000, 32, 32, 3)
(10000, 32, 32, 3)
(10000, 1)
[0 1 2 3 4 5 6 7 8 9]


In [4]:
# preprocessing the data
# One-hot encoding for the labels -> it will be replaced by arrays with 1s and 0s
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)


In [5]:
print(y_train.shape)
print(y_train)
print(y_test.shape)
print(y_test)

(50000, 10)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
(10000, 10)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [6]:
# normalize the data
X_train = X_train/255.0
X_test = X_test/255.0

In [7]:
#@title 기본 제목 텍스트
model = Sequential()
# kernel_initializer : random weight initializer
model.add(Conv2D(32, (3, 3), activation = 'relu', kernel_initializer='he_uniform', padding='same', input_shape = (32,32,3)))
model.add(BatchNormalization())
model.add(Conv2D(32, (3, 3), activation = 'relu', kernel_initializer='he_uniform', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2, 2))
model.add(Dropout(0.2))

model.add(Conv2D(32, (3, 3), activation = 'relu', kernel_initializer='he_uniform', padding='same'))
model.add(BatchNormalization())
model.add(Conv2D(32, (3, 3), activation = 'relu', kernel_initializer='he_uniform', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2, 2))
model.add(Dropout(0.2))

model.add(Conv2D(32, (3, 3), activation = 'relu', kernel_initializer='he_uniform', padding='same'))
model.add(BatchNormalization())
model.add(Conv2D(32, (3, 3), activation = 'relu', kernel_initializer='he_uniform', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2, 2))
model.add(Dropout(0.2))


model.add(Flatten())
model.add(Dense(128, activation = 'relu', kernel_initializer='he_uniform'))
model.add(Dense(10, activation='softmax'))

# train the model using optimizer variable
optimizer = SGD(learning_rate=0.001, momentum = 0.95)

# compile the model
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=50, batch_size=64, validation_data=(X_test, y_test), verbose=2)
## 존나 오래 걸리네 ㅅㅂ
# 정확도도 낮어 -> Regurarization

Epoch 1/50
782/782 - 278s - loss: 1.7114 - accuracy: 0.3886 - val_loss: 1.3435 - val_accuracy: 0.5092
Epoch 2/50


KeyboardInterrupt: ignored

In [ ]:
# Evelutate the model
model_result = model.evaluate(X_test, y_test, verbose = 0)
print("Accuracy of CNN model: %s" % (model.result[1] * 100.0))