In [1]:
import numpy as np
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import OneHotEncoder
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from keras.optimizers import Adam
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
dataset = load_iris()

features = dataset.data
y = dataset.target.reshape(-1,1)
print(features[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [3]:
encoder = OneHotEncoder()
targets = encoder.fit_transform(y)
# y has output of 0, 1, 2
# transform output to (1, 0, 0), (0, 1, 0), (0, 0, 1) -> 3 output nodes
print(targets.toarray()[:10])
print(encoder.categories)


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
auto


In [4]:
train_features, test_features, train_targets, test_targets = train_test_split(features, targets, test_size=0.2)

In [5]:
print(train_targets.toarray()[:10])

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [6]:
model = Sequential()

model.add(Dense(64, input_dim=4, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))

# Dense(# of hidden layers, input_dim, ...)

In [7]:
optimizer = Adam(learning_rate = 0.005)

In [8]:
print(type(train_features))
print(type(test_targets))
test_targets = test_targets.toarray()
train_targets = train_targets.toarray()

<class 'numpy.ndarray'>
<class 'scipy.sparse.csr.csr_matrix'>


In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer=optimizer,
              metrics=['accuracy'])

model.fit(train_features, train_targets, epochs=1000, batch_size=20)
results = model.evaluate(test_features, test_targets)

In [20]:
score = model.evaluate(test_features, test_targets)
print("loss : %.2f" %score[0])
print("accuracy : %.2f" %(score[1]*100))

1/1 [==============================] - 0s 19ms/step - loss: 0.0636 - accuracy: 0.9667
loss : 0.06
accuracy : 96.67
